- v86.css
Without this change, underscore (being under the baseline in Liberation Mono and Courier New), is not showing.
> fix underscore not showing on Ubuntu

- src/cpu.js
Tested on Mac OS X 10.11 El Capitan & Safari 9.0.
> Remove duplicate init code in src/cpu.js

- .gitignore
- tests/full/run.js
Set longer timeout to prevent some test failures on some slower operating systems.
Additionally change .gitignore
> Set longer timeout for test cases

- Readme.md
Looks like the file is now called `closure-compiler-v20170423.jar`
instead of `compiler.jar`. This appears to already have been corrected in
the Makefile [here](https://github.com/vdloo/v86/blob/master/Makefile#L142).
> fix unzip command in readme

- docs/events.md
- docs/filesystem.md
points to `master/docs/docs/api.md` currently
> fix docs links to api.md

- docs/linux-9p-image.md
The "$root" should always be host9p if you want to boot with the root fs mounted over 9p, otherwise the initcpio hook will try to mount /dev/sda1 (or whatever you have configured) over /new_root as a 9p fs (which it maybe isn't) and the system will complain with "no channels available" and drop you in the emergency shell without any real clues about what is going on. I think you can probably achieve this with "$root" as well by grub installing 'host9p' as the root fs or doing what @ysangkok does https://github.com/copy/v86/issues/41 but I think that in the case of the specific linux-9p-image doc it makes more sense to hardcode it in  the hook since it should never be anything other than host9p. Took me a while to figure out this was what was causing my machine to fail to boot since the …
> update linux 9p image mount hook doc

- src/fpu.js
This PR only aims to allow the `fprem` instruction to update the condition codes in the FPU status word. This allows the `fprem` instruction to actually complete instead of looping waiting for `C2` to be reset to `0`.
**Note:** Doesn't take into account exceptions, nor does it emulate the way `fprem` actually calculates the partial remainder (by iteration).
> Improve fprem instruction implementation to update FPU status word's condition codes

- .travis.yml
I haven't seen this one work yet so it makes sense to me to allow this one to fail. (now we can add the badge without v86 looking bad because of builds "failing")
You see my issue here? Both PRs will build and work fine, but the VGA PR will be shown as failing because of a test that isn't affected by it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/copy/v86/181)
> Allow the QEMU test to fail

- src/browser/keyboard.js
Firefox 57 and Edge 41 on Windows (tested on Windows 10) do not emit keyup event for the alt key when the alt key is pressed with other keys, although Firefox on Ubuntu *does* appears to emit the event. Interesting how older versions of Firefox *do* seem to emit the event too. See #165.
This patch is tested on Firefox (Ubuntu Xenial in a VM and Windows 10) and Chrome. Haven't tested on Apple and with other browsers.
Possible bug with the web browsers? If it is, it might be better to close this PR and wait until they fix it rather add noisy code that adapts to their bugs... if we don't mind keeping v86 in a buggy state while we wait that is.
**Update:** Edge Alt keyup sometimes fires, sometimes doesn't. Strange. https://jsbin.com/vocehicipe/6/edit?html,js,output
Related: …
> Detect and trigger Alt-Key keyup, fixes #165

- .editorconfig
- docs/events.md
- src/browser/main.js
- src/browser/screen.js
- src/config.js
- src/state.js
- src/vga.js
- VGA write modes 0, 1, 2, 3 with set/reset, planar rotation.
- VGA write using single dword to represent all 4 plane bytes.
- VGA read mode 1.
- Provides a workaround solution to issues #110 and #90 (sacrificing the performance and resolution of the vbe driver for normal vga)
**Update:** this PR now also includes:
- VGA chain odd/even and interleaved shift - implements modes 4h and 5h.
- VGA unchained, chain 4 256 color shift - implements modes 13h, mode X.
- VGA panning, page flipping, split screen.
- VGA palette redraws.
(This is the same video as the one for sb16 PR)
https://drive.google.com/file/d/1FSt14j7ayKnaT7AS8lF_4S1i4ZX9GlEk/view
(the demo also contains code for 320x400 display mode that is not included with this PR)
- I'm curious to see if you like how the modes are …
> Implement VGA graphical behaviour on per-register basis

- .gitignore
- .travis-run-integration-acpi.sh
- .travis.yml
- Makefile
- src/config.js
This pull request adds..
- An ACPI test on travis
- The build option to enable ACPI `useacpi=true` ex: `make build/libv86.js useacpi=true`
- .DS_Store added to the .gitignore because it was annoying me
Thanks for the help with git, you guys are great
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/copy/v86/186)
> ACPI test for travis

- lib/9p.js
`SETATTR` system calls that set a custom atime on an inode (e.g., `touch -t 0102030405 a.txt`) set both the `SETATTR_ATIME` and `SETATTR_ATIME_SET` flags.
Prior to the fix, SETATTR_ATIME_SET was processed first, setting the custom `atime` correctly.
Then, SETATTR_ATIME was processed, which updated the `atime` to the current time.
This execution order was essentially overwriting the custom `atime` immediately. The fix executes the two instructions in the correct order, and fixes a typo (an `atime` that should have been an `mtime`).
Before the fix:
```
root@host ~ >> touch -t 0102030405 a.txt                                    
root@host ~ >> stat a.txt                                                   
File: a.txt                                                                   
Size: 0 …
```
> 9P filesystem allows to set custom atime and mtime

- src/ps2.js
Alternative to PR #184 for fixing #182.
Two main changes to master branch:
1. Pulse interrupt lines to ensure rising edge.
Supports for pulse:
- [Under *Interrupt Processing*, paragraph 2, from here](http://www.os2museum.com/wp/ibm-ps2-model-50-keyboard-controller/)
- [Paragraph 1 from here](https://wiki.osdev.org/8259_PIC#What_does_the_8259_PIC_do.3F)
Against pulse:
- [Under *Reading Keyboard Input*, paragraph 2, from here](http://www.computer-engineering.org/ps2keyboard). It says that the interrupt is cleared after reading port `0x60`. It might be referring to AT controllers instead of PS/2.
2. Before data in port `0x60` gets read, don't switch between `kbd` and `mouse` queues.
In hardware terms: inhibit keyboard and mouse communication and don't overwrite the `DBBOUT` output buffer …
> Handle simultaneous keyboard and mouse streams - Alternative 2

- src/browser/main.js
- src/browser/speaker.js
- src/const.js
- src/externs.js
- src/lib.js
- src/pit.js
- src/sb16.js
Good grief. I made another ginormous PR.
- Implements the mixer chip.
- Fixes several SB16 bugs.
- Refactors Speaker Adapter into smaller components:
- PCSpeaker - *responsible for the beeping sounds and [really awesome retro game music](https://drive.google.com/open?id=1ErJTdOOKkfNHhk4_Sq2gLosfcn1P4C5I)*.
- DAC - *responsible for queuing and continuously playing audio data - such as Windows 98 sounds and Doom sound effects*.
- Mixer - *responsible for mixing, panning, and boosting the audio from PCSpeaker and DAC*.
- The mixer amplifies audio aliases from my naive sample rate converter (which sounds horrible), so I decided to fix the sample rate conversion using the following...
- Removes the deprecated `ScriptProcessorNode`-based DAC, and
- Reimplements the DAC component using …
> Implement SB16 Mixer Chip + Several Speaker Improvements

- src/browser/speaker.js
A proposed fix for #216 
Haven't had this tested on Safari ironically.
(Sadly I don't have access to a Safari on a desktop)
> Unchain AudioNode#connect methods to support Safari

- src/browser/speaker.js
- src/sb16.js
Fixes #286 for Safari.
Tested on my friend's iPad and at least it doesn't hang when trying to play audio.
This PR also fixes a bug where restoring emulator state loads the wrong volume values, causing the Windows 98 demo to be silent until the volume is manually readjusted in the guest OS.
> Fix state-restore mixer volume bug and Safari hang bug

- src/arith.js
- src/cpu.js
- src/instructions.js
- src/lib.js
For integer multiplication, direct product of two 32-bit integers in
double precision FP arithmetic yields its higher 53 bits which are
sufficient for higher half of the product, while the lower half may be
computed with `Math.imul()`. A polyfill is provided for < IE 10.
For `floor(log2(n))` where `n` is a 32-bit integer, `31 - Math.clz32(n)`
is an accurate substitute for `v86util.int_log2` and preserves
`int_log2(0) = -1` (should it ever occur).
> Use ES intrinsics for mul / imul, bsr / bsf

- src/browser/keyboard.js
This is a temporary solution for hardcoded `className` in keyboard handler.
---
Previously, `className` have to only contain `phone_keyboard` and nothing else. So if the element contained also other classes, it won't be handled.
It now checks if `className` includes `phone_keyboard` so element can now also use other classes.
---
A complete solution would be to completely drop `className` check and instead check if the element is a child element of screen container. This would enable handling all elements in the screen container.
This can be done with `screen_element.contains(e.target)`. The reason why I didn't use this in this PR is that `screen_element` isn't available in the keyboard adapter. To fix this, adapters need to be modified to accept and use `V86Starter` options which contain …
> Temporary solution for hardcoded className

- examples/lua.html
Previously, tabulators (\t) would escape the CLI input into `lua -e` and cause unknown output. See #217 
To remedy, the input must be escaped from tabs before escaping special characters into quotes. 
Tested inputs with correct output:
```
k = 1
x = 0
while k < 1000 do
x = x + 1 / (k * k)
k = k + 2
end
print(math.sqrt(x*8))
function factorial(n)
if n == 0 then
return 1
else
return n * factorial(n - 1)
end
end
print("factorial(10):", factorial(10))
```
`	` (\t)
`		` (\t\t)
```
print("1")
print("2")
```
> Fix tabulators from escaping CLI (#217)

- Makefile
Using an older version of closure to allow builds to succeed instead of using lastest version of closure
> use specific version of closure

- src/instructions.js
The instruction encodings are:
`F3 0F 1E FA` for `ENDBR64` and `F3 0F 1E FB` for `ENDBR32` respectively. 
Therefore. this PR should handle these instructions by:
- Not raising an assert, and
- Gracefully ignore the extra byte
This obviously does not handle all the CET instructions for https://github.com/copy/v86/issues/343, but it deals with the most obvious case.
> An attempt to make v86 ignore endbr32/endbr64 instructions

- debug.html
- src/browser/main.js
- src/cpu.js
- src/ide.js
Fix #353 
This allows a second hard disk to be connected as a slave.
> Exposing the option to specify the second hard disk as a slave

- .github/workflows/release.yml
It doesn't make sense to release ACPI builds when they aren't the default, also, release `v86_all.js` so people can use the included `index.html` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/copy/v86/367)
> Don't release ACPI builds, also include v86_all.js 

- src/browser/keyboard.js
Before the change, the scan code for Home was the same as for End. I've replaced the lower byte with a correct one (0x47) as per [this page](https://www.fountainware.com/EXPL/bios_key_codes.htm).
> Replaced the scan code for Home with the correct scan code.

- src/ne2k.js
I believe this fix should enable the use of the network card under Windows! I've tested it in Win98 so far.
The fix is includes two components, both based simply on comparing to the logic in the working qemu implementation.
1. The initial buffer setup appears to be incorrect. The 0x57 byte should be set on bytes 28 through 31.
This is simply by comparing to what qemu does in: https://github.com/qemu/qemu/blob/master/hw/net/ne2000.c#L130
I think this is the crux of the fix!
2. The write logic is also slightly off. In qemu's implementation, the command register is always set, and then bitwise op is applied if condition is met: https://github.com/qemu/qemu/blob/master/hw/net/ne2000.c#L281
Also changed an | to and & to match.
I am no expert on this card, basically just compared to what QEMU …
> Ne2k Driver Fixes to Support Running in Windows!

- src/rust/cpu/cpu.rs
Right now jit_run_interpreted may exit on any instruction causing a new entry point to be created at the exit location. This patch avoids that by waiting for a backward jump to exit the function. This in turn avoids unnecessary entry points and unnecessary BB splitting.
> avoid ending jit_run_interpreted in the middle of a basic block

- Readme.md
- tools/docker/README.md
- tools/docker/exec/Dockerfile
- tools/docker/exec/build.sh
Uses Alpine image as base to have minimal size. 2-step build process to get rid of source and library files after compilation and during runtime. Uses Python3 HTTP Server to serve static assets.
Signed-off-by: Progyan Bhattacharya <bprogyan@gmail.com>
> (feat) Docker: Add Support for Running inside Docker Container

- Readme.md
Hi again,
Building inside Docker is super great! I fixed a simple typo of `docker run`.
> fix `docker run` command in README.md

- tools/docker/debian/Dockerfile
- tools/docker/debian/build-container.sh
- tools/docker/debian/build-state.js
Hi,
I fixed `tools/docker/debian` to build debian image. `FROM i386/debian` causes errors, "... bullseye-security InRelease' is not signed.", so I specified `:buster`. I added `../` to `build-container.sh` and `build-state.js`.
One thing I'm not sure is the following statement in tools/docker/debian/Readme.md.
> Go to debug.html?profile=debian to start the generated container.
I don't know how to start the built debian. I confirmed I could run the built debian, modifying examples/arch.html instead.
But anyway, this PR fixed building of debian.
> Fix debian build

- Makefile
This attempts to work around #562 by moving the block-size option in ls to an environment variable
> fix build on MacOS

- src/browser/main.js
- src/const.js
- src/debug.js
- src/rust/cpu/cpu.rs
- src/rust/cpu/instructions_0f.rs
- src/rust/cpu/memory.rs
- tests/kvm-unit-tests/README.md
- tests/kvm-unit-tests/x86/Makefile.common
- tests/kvm-unit-tests/x86/pae.c
Physical memory is still limited to 32-bit addresses, but systems that enable PAE should work now.
I managed to boot the Ubuntu 12 ISO. However, it takes a lot of time to start and is too slow to do anything...
(During the boot, it complains about `soft lockup - CPU #0 stuck for 23s!`. Apparently it happens during the inintrd decompression `unlzma`, because it's pretty slow. However, if you just wait, it should go through).
PAE also should unlock Serenity OS. I tried it, but there are still some issues. After applying some workarounds, I managed to boot it and it looks like it initializes network, mouse, and starts various processes. However, graphics fail to display. I'll post an update later.
> Add support for PAE (#97)

- docs/archlinux.md
- docs/networking.md
Based on updates described in #485 and #558.  `provisioning.sh` of https://github.com/copy/v86/issues/485#issuecomment-860002163 is used with `mkinitcpio -p linux` added back into `/mnt/bootstrap.sh` (otherwise added kernel modules don't seem to load)  Additionally throttling note is added to `networking.md` docs.
Let me know if this makes sense, and whether anything else needed here.
> Update archlinux build docs

- src/browser/screen.js
2x Scale graphic display only when 
- Guest system running in low resolution (width <= 640) graphic mode
- Host browser has enough window size to show 2x scale.
> Only scale display when window big enough (#622)

- src/browser/starter.js
Make same dirname for `v86_bin_fallback` and `v86_bin` paths. It is needed when defined options["wasm_path"].
> fix v86_bin_fallback full path: getDirname (2)

- src/browser/starter.js
Some bundlers allow directly importing a .wasm file ([https://vitejs.dev/guide/features.html#webassembly](https://vitejs.dev/guide/features.html#webassembly)).
This modification to the starter would allow receiving the wasm file via an import:
```js
import v86Wasm from "../build/v86.wasm";
const emu = new V86Starter({
wasm_fn: v86Wasm,
});
```
> Allow receiving wasm as a function via wasm_fn

- src/vga.js
> Add dac_mask to fix text mode color

- src/ps2.js
I've looked in the [ps2 qemu code](https://github.com/qemu/qemu/blob/master/hw/input/ps2.c) and changed something.
About Windows NT 4.0:
It sends 200->100->80 to use 0x03 mouse mode, then it resets mouse and mouse_id is now 0x00. But windows is still working like with 0x03 mode.
But then it sets rate to 60, so, let's detect 200->100->80->60 and turn on workaround mouse_id reset.
In the qemu it's as working as well without any fixes.
But windows with SP6 uses default 0x00 mouse type (it's changing rate 20->40->60->60), so, that can be partically a windows bug.
> PS2 wheel improvements + winnt fix

- src/config.js
- src/vga.js
I don't know how, but I've randomly fixed it.
Before:
After:
> DAC Fix for Win9x bootlogo progressbar

- examples/debian.html
- src/browser/main.js
- tools/docker/debian/Readme.md
- tools/docker/debian/build-container.sh
This MR addresses 2 issues:
You need to add a new profile into main.js file in order for http://localhost/debug?profile=debian to load something, otherwise it just loads default debug page instead of actual image.
Error looks like this: 
> WARNING: The requested image’s platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
Adding platform in the build script explicitly fixes the issue.
ps: I guess I should have opened separate merge requests for each issue...?
> Update Debian build info

- lib/9p.js
- src/browser/main.js
The 9p filesystem is always accessible by the guest, even if the UI is hidden. This will make the file picker UI be shown when needed; all the user has to do is run `ls` on the 9p mount.
> Allow sharing files with guest using UI, even with custom profile

- Readme.md
SkiffOS is a configuration layering system for Buildroot.
It supports re-targeting system image configs to different hardware.
The linked configuration can be combined with other layers to deploy Docker and other Linux distributions to the v86 emulator.
The configuration fragments slim down the Buildroot and Kernel systems & switch off any unnecessary features.
https://github.com/skiffos/SkiffOS/tree/master/configs/browser/v86
Demo ISO: https://drive.google.com/file/d/1UFoUEt1CQrD8B4800ii9yehff68h9IPG/view
V86 is really awesome & I was really floored to see that everything could run in it with minimal adjustments.
> readme: add SkiffOS (Buildroot) config link

- src/browser/starter.js
- src/main.js
In some environments, the "emulator-stopped" event did not always fire when calling the `destroy()` method. This waits for emulation to finish stopping before continuing with the rest of the destructor.
My use case, for more context:
I'm running v86 in a React app, and the page does not reload between destroying one emulator instance and starting another. Setting event listeners for the "emulator-stopped" event seemed to prevent garbage collection, so it quickly consumed lots of memory and would crash the browser tab.
> Wait for emulation to stop when destroying

- src/browser/serial.js
- src/bus.js
`V86.destroy()` was throwing an error due to `SerialAdapterXtermJS`
having no `destroy()` method.
> Fix V86.destroy() with xterm.js

- Readme.md
After #299 was resolved (thanks for your awesome work!), we can simply advertise SerenityOS target as working in the README.md file.
> Advertise latest SerenityOS version as working

- src/browser/starter.js
- src/buffer.js
This allows reducing the number of separate HTTP requests, which considerably improves load times at the cost of increased bandwidth use. Tested locally, to a limited extent.
> Add support for fixed_chunk_size to async Range downloads.

- docs/networking.md
I've deleted that docker hub account and that image is now published under `bellenottelling/websockproxy`
> Correct docker image for no limiter

- src/browser/screen.js
To match the rest of the character set currently used (appearing to be Code page 437), VGA text modes should output ⌂ for 0x7F rather than a 0x7F (DEL) character. This prevents the VGA text output from losing a character in the output when an on screen character is 0x7F, and brings the text display in line with behavior on most real hardware.
> VGA text mode should display ⌂ for 0x7F, not DEL.

- src/browser/main.js
- src/browser/screen.js
- src/browser/starter.js
Returning an image rather than always opening a new window slightly expands the utility of embedding v86---we may want to take a screenshot and use just its data without asking the user to download it.
> Make screenshot function return an Image

- src/browser/keyboard.js
Maps the [IntlRo key](https://www.w3.org/TR/uievents-code/#keyboard-104) to the slash key in the keyboard codemap
Fixes #831
> Map IntlRo key to Slash

- gen/x86_table.js
- src/rust/cpu/instructions_0f.rs
- src/rust/jit_instructions.rs
This PR adds the HADDPS instruction, which fixes [this issue](https://github.com/copy/v86/issues/835). This allows the KolibriOS Raytracing demo to run. Numeric exceptions aren't implemented.
Documentation:
- https://c9x.me/x86/html/file_module_x86_id_133.html
- https://www.felixcloutier.com/x86/haddps
> Implement HADDPS instruction

- Makefile
- debug.html
- index.html
- src/browser/main.js
- src/browser/starter.js
- src/buffer.js
- src/cpu.js
- src/floppy.js
- src/rtc.js
- tests/api/floppy-insert-eject.js
This patch implements two new methods on FloppyController, `eject_fda` and `insert_fda`.  These are not exposed to the UI yet, but from the browser console in debug mode they work for removing and inserting floppies in MS-DOS at least.
Caveats:
1. FloppyController does not implement the format track command, so you need to give it a pre-formatted disk image.
2. FloppyController does not seem to emulate all the relevant internal controller state, so I made a best-effort patch here (references: [this website](https://www.isdaman.com/alsos/hardware/fdc/floppy.htm) , [osdev](https://wiki.osdev.org/Floppy_Disk_Controller) ).  I did what I could around reset behavior, extending existing commands, and reporting errors on seeks and reads, but this is pretty far outside my wheelhouse.
So, please …
> Floppy eject/insert

- src/browser/main.js
This small change just incorporates the usage of the browser's local storage to remember and restore a handful of options for a minor increase to the overall quality of life.
Namely it saves and restores:
1. System memory size 
2. Video memory size
3. The networking proxy that's configured (saving this will be rather nice if testing a local one)
4. The boot order
5. If audio is enabled
6. If ACPI is enabled
Worst case, this doesn't save info in a way that someone finds helpful and they have to change the value as they would have normally. Best case, people re-use the config for a bunch of different testing and this change saves them a bit of clicks / keystrokes.
> Use localstorage to save options

- src/buffer.js
- src/lib.js
When v86 needs to load a chunk of a file, it can silently download garbage if the server is using gzip encoding (it gets a range, but of the wrong data).  This patch does two things:
1. Error out instead of proceeding if the content-encoding of a download after a range request exists and is not "identity".
2. Send the nonstandard "X-Accept-Encoding: identity" header when making range requests.
We can't use `Accept-Encoding` because it's on the forbidden header list, but some web servers respect `X-Accept-Encoding`.
> More graceful HTTP content negotiation

- Readme.md
Read the title to see what this PR is about :)
> Update Readme.md to specify operating system compatibility in Virtual x86

- Readme.md
I stumbled across a minor imperfection in the README: both SkiftOS and SkiffOS are mentioned, but the former has no entry in the compatibility list, and the latter has no profile linked in the demo list (but there apparently is one). This might confuse some users (like me) :D
I quickly fixed this by adding the two lines.
> Both SkiffOS and SkiftOS are mentioned in the readme, but it's kinda mixed up.

- .github/workflows/ci.yml
Fixes publishing build artifacts into the latest release and also builds and includes the fallback wasm build.
> Fix release artifact upload.

- Readme.md
- docs/archlinux.md
- docs/cpu-idling.md
- docs/filesystem.md
- docs/linux-9p-image.md
- docs/networking.md
> Improve documentation some more

- src/const.js
- src/cpu.js
- src/elf.js
- src/io.js
- src/kernel.js
This fleshes out the multiboot support a bit more. My hobby os relies on multiboot, but also needs some ACPI tables set. Using the existing multiboot support means seabios doesn't run at all, and the tables are missing.
The multiboot content is loaded in an i/o write hook rather than before booting, because otherwise seabios may overwrite the loaded data (happens with the kvm-test).
load_multiboot still works, although the mechanism changed, because nasmtests uses it directly and doesn't load seabios anyway. Now it generates the option rom, loads it at address 0 (seemed like a convenient place) and adjusts execution to start at address 3 (where an option rom is jumped to in a BIOS context).
There's a not entirely related log fix in elf section header debug info (log said program headers, …
> change multiboot to boot as an option rom, add initrd, cmdline

- src/browser/starter.js
- src/uart.js
This PR adds modem status functionality to UART.js. A couple of use cases for this:
1) Running a retro BBS system or BBS door game within a browser or node.js
2) Running old DOS modem terminal programs - part of what is needed for Issue #138
...or anything else that uses the UART that expects flags such as carrier detect, etc to be set.
> Add modem status functionality to UART class

- src/vga.js
There's not a whole lot of use of these registers in text mode in the wild, but crazierl uses it, so I'm motivated. :)
Math.max(this.max_cols, this.offset_register * 2) is a bit of a cop-out, I think VGA user should likely be properly setting the offset register, but I didn't want things to fail in case they don't.
> vga: support line_compare and offset_register in text mode

- src/virtio_console.js
I discovered that all virtio console data was getting sent to the same port (`/dev/hvc0`) when doing something like this:
```js
const encoder = new TextEncoder()
emulator.bus.send('virtio-console1-input-bytes', encoder.encode('hello world 1\n'))
emulator.bus.send('virtio-console2-input-bytes', encoder.encode('hello world 2\n'))
emulator.bus.send('virtio-console3-input-bytes', encoder.encode('hello world 3\n'))
```
When looking at the code, I noticed that the variable `queue` (the first one) is unused. I renamed it to `queue_id` (because there's another `queue` variable inside the event listener), plugged it into where it looked like it should go, and it worked :)
> Virtio console: Send bytes to the right queues

- src/ps2.js
Add hexadecimal prefix to identify response's second byte. Now PS/2 keyboard responds with the correct identification bytes 0xAB, 0x83.
> Fix PS/2 keyboard identify response

- src/ps2.js
PS/2 keyboard reported current scan code set as 2 while only scan code set 1 was emulated.
> Report current PS/2 scan code set as 1

- src/rust/cpu/cpu.rs
If page directory was present and ring3 access or write protection violation caused page fault on page directory level, page presence was not checked and it was assumed to be present.
This PR adds this check to correctly report present bit in page fault error codes.
I found this bug as my OS uses the present bit in error code of page fault as the initial requirement for demand paging.
This is my first time writing rust, so please tell me if something should be done differently.
> PageFault error code now reports page presence correctly

- src/browser/dummy_screen.js
- src/browser/screen.js
- src/vga.js
- v86.css
1. Add BLINK flag support (3rd bit in VGA Attribute Mode Control Register).
> When this bit is set to 0, the most significant bit of the attribute selects the background intensity (allows 16 colors for background). When set to 1, this bit enables blinking.
A test program which writes a blinking text to the text buffer
```
org 100h
mov ax, 0xB800 ; text buffer address
mov es, ax     ; segment register points to the text buffer
xor di, di     ; text buffer offset
mov ah, 0x92   ; XRGBIRGB, X-blink, RGB-bg, I-intensity, RGB-fg
xor bx, bx     ; text buffer index
mov cx, len    ; message length
mov bp, msg    ; message address
print:
mov al, [bp]            ; put next char from msg to al
mov word [es:di+bx], ax ; direct write to the text buffer
add bx, 2               ; video memory cell is …
```
> Text Mode enhancement

- src/vga.js
Fixes #641, tested on https://old-releases.ubuntu.com/releases/4.10/warty-release-live-i386.iso and https://cdimage.debian.org/debian-cd/current/i386/iso-cd/debian-12.6.0-i386-netinst.iso
> vga: clear memory if VBE_DISPI_NOCLEARMEM is not set

- src/browser/filestorage.js
- src/browser/starter.js
- src/cpu.js
This fixes using v86 in bundlers like vite.
> Export as a module first

- src/browser/keyboard.js
Remove ControlLeft from keyboard input sequence `ControlLeft + AltRight` if platform is Windows and `AltRight` is pressed.
See issue #1127 for more details.
> Remove spurious ControlLeft-key when AltRight is pressed under Windows

- src/vga.js
Adds support for horizontal offset in Bochs VESA BIOS Extension.
Should fix issue #1088.
> Add support for VBE_DISPI_INDEX_X_OFFSET

- .github/workflows/ci.yml
Mentioned in Gitter chat, should prevent CI from getting stuck for 6 hours.
> ci: set 1 hour timeout for "Build and test" job

- .github/ISSUE_TEMPLATE/issue.md
- Readme.md
- docs/windows-9x.md
Mentioned issues: #945, #1003 and #1101.
> docs: adding instructions for Windows 9x

- src/browser/fetch_network.js
- tests/devices/fetch_network.js
Currently, I have only seen this bug in older versions of Dillo, but it's possible that other HTTP clients have it too.
**Test-case**: boot from https://distro.ibiblio.org/damnsmall/current/current.iso with enabled fetch networking and then try to open any page in Dillo, you get in the browser console:
```
TypeError: Headers.set: accept-encoding:gzip is an invalid header name.
```
A raw HTTP request from Dillo looks like this:
```http
GET / HTTP/1.0
Host: copy.sh
User-Agent: Dillo/0.8.5-i18n-misc
Accept-Language: en-us, ja
Accept-Encoding:gzip
Accept-Charset:utf-8,ISO8859-1
Cookie2: $Version="1"
```
According to [RFC 2616 (section 4.2)](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2), HTTP client/server can use any amount of whitespaces after separator, previous code expected …
> fetch-networking: fix parsing of HTTP headers

- src/browser/fetch_network.js
- src/browser/main.js
- src/browser/starter.js
- src/browser/wisp_network.js
Extends the syntax of relay_url for fetch to:
fetch[:CORS-PROXY-URL]
where CORS-PROXY-URL is a full URL pointing to the CORS proxy server, for example:
fetch:https://example.com/?url=
Fixes issue #1188.
> Allow embedding of CORS proxy in fetch relay_url

- Readme.md
- examples/broadcast-network.html
From #1094, including a few toy network services (DNS, HTTP, Telnet servers) for testing.
> examples: add "Networking between browser windows/tabs using the Broadcast Channel API"

- src/browser/network.js
Stops NetworkAdapter from reconnecting to its Websocket proxy server after V86 was shut down.
> Stop reconnecting websocket after NetworkAdapter.destroy() was called

- tools/docker/alpine/Dockerfile
- tools/docker/alpine/Readme.md
Changed the default kernel flavor to `virt` and added virtio-net support
> alpine: update to 3.21.0

- .github/workflows/ci.yml
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ and https://github.com/actions/cache/discussions/1510
> ci: update actions from v3 to latest v4

- src/browser/fake_network.js
- src/browser/fetch_network.js
- src/virtio_net.js
- tests/devices/fetch_network.js
Allows connection to servers running inside the VM from javascript.
- Move fetch_networking tests from linux4 to buildroot68
- Add a test talking to a TCP server inside the VM
- Add back fetch_adapter.fetch override for fetch()
- Fix fetch mocking test
- Fix virtio_net's mac address preservation logic.
> tcp connect

- src/browser/fake_network.js
- tests/devices/fetch_network.js
Fixes "different address" warning in busybox's `ping` on [buildroot6](https://copy.sh/v86/?profile=buildroot6&relay_url=fetch):
```
~% ping -c 4 1.2.3.4
PING 1.2.3.4 (1.2.3.4) 56(84) bytes of data.
64 bytes from 192.168.86.1: icmp_seq=1 ttl=32 time=2.10 ms (DIFFERENT ADDRESS!)
64 bytes from 192.168.86.1: icmp_seq=2 ttl=32 time=1.84 ms (DIFFERENT ADDRESS!)
64 bytes from 192.168.86.1: icmp_seq=3 ttl=32 time=1.06 ms (DIFFERENT ADDRESS!)
64 bytes from 192.168.86.1: icmp_seq=4 ttl=32 time=1.42 ms (DIFFERENT ADDRESS!)
```
> fake-network: fix incorrect source IP for ICMP

- src/cpu.js
- src/rust/cpu/memory.rs
- tests/benchmark/snapshot.js
As suggested by @copy  in #1219 move the check if a memory page is all zeros to rust.  Executes on 64bit chunks, which is likely not as good simd could do, but is still a 5x speedup in the included snapshot benchmark on my machine.
Co-authroed-by: @rndmcnlly for the original idea
In the final version the bitmap can be done in rust as suggested, however until thats worked out we might as well get this basic acceleration in as its such a huge improvement over whats there now.
> Optimize pack_memory by moving zero check to rust.

- Makefile
- nodejs-loader.mjs
- src/browser/fetch_network.js
- src/browser/print_stats.js
- src/browser/starter.js
- src/lib.js
This fixes compatibility issues when used with vite inside a service worker, and should be a bit more idiomatic in general.
> Convert exports to closures export system and add a ES6 module build.

- src/browser/fetch_network.js
The original code in `fetch_network` binds `fetch` to `FetchNetworkAdapter`. In many modern browsers (including Chromium), binding `fetch` results in a `Illegal invocation` error.
An alternative solution to fix this would be to just call `globalThis.fetch()` or `fetch()` directly in the adapter but I didn't want to touch on any toes in case having a method on the prototype is useful for anyone.
> fix: Invalid invocation of fetch()

- src/virtio_net.js
I noticed plenty of `No buffer to write into!` console messages when putting high pressure on virtio_net.js. For example, when booting my [iSCSI-experiment](https://github.com/copy/v86/discussions/1254) there are 808 of these messages directly after login.
This message is generated in the [net-receive bus message handler](https://github.com/copy/v86/blob/ec3ecde20335eb1f162c7141c1b4fbd36483dd7e/src/virtio_net.js#L191-L207) of virtio_net when its preallocated set of buffers is exhausted, causing the handler to drop the ethernet frame instead of handling it.
The number of preallocated buffers is determined by the size of the send- and receive-queues passed into the [VirtIO-constructor in virtio_net.js](https://github.com/copy/v86/blob/ec3ecde20335eb1f162c7141c1b4fbd36483dd7e/src/virtio_net.j …
> Relax bottleneck in VirtIO network adapter

- tools/copy-to-sha256.py
- tools/fs2json.py
> fix opening folder in `fs2json` and `copy-to-sha256` on Windows

- Readme.md
- docs/networking.md
- examples/tcp_terminal.html
Added an example of connecting to a TCP guest port from JS API
> add "tcp terminal" example for fetch-based networking

- src/browser/main.js
Currently, the different guest OS filters are logically combined in function `update_filters()` by `OR`-ing them together.
This patch splits filters into the same categories that are already defined in the UI (`Family`, `UI`, `Medium`, ...). Filters within a category are logically combined using `OR`, and categories are then combined using `AND`.
Note that the web UI DOM is left unchanged by this patch.
Fixes issue #1268.
> Fine-tune OS filter behaviour in web UI

- src/virtio_console.js
- tests/devices/fetch_network.js
- Use the response contructor in the fetch unit tests instead of faking it
- Allow setting size of multiple virtio-consoles independently
> Small fixes

- src/cpu.js
- src/ps2.js
Added PS/2 to devices which are reset in CPU.reboot_internal().
- Moved assignment of all member variables from constructor to new method PS2.reset().
- Added call to PS2.reset() in PS2 constructor and in CPU.reboot_internal().
Fixes issue #1300.
> Reset PS/2 runtime state when soft-resetting CPU

- src/vga.js
> distinguish 8-, 4- and 1-bit color modes for non-SVGA graphics modes

- debug.html
- index.html
- src/browser/main.js
- src/browser/starter.js
- src/cpu.js
- src/ide.js
- src/pci.js
This is the same as #1325, with three extra changes:
- eb9f20dd7dcd30ca7f83d06c491d3b47efae61e4     make ide changes compatible with old state images 
- 57feb57 minor cleanup
- rebased to remove merge commit
@chschnell Could you do a quick review of this? An alternative would have been to layout the ide controller the same as previously (CD-ROM primary if there is no hard disk), but I slightly prefer having the CD-ROM always as the secondary.
> Improve IDE Controller (rebased + fix for old state images)

- docs/filesystem.md
- lib/9p.js
- lib/filesystem.js
- src/browser/starter.js
- src/cpu.js
- v86.d.ts
This is an initial pass at allowing a custom 9P handler function to be provided that would be used by Virtio9p instead of the HTTP backed filesystem. It's based on a working patch used by [Wanix][1]. It compiles but hasn't been thoroughly tested yet. I'd like feedback on implementation/API and how much testing would be appropriate. I can provide an example/test that's based on a Wasm 9P file server written in Go if that would be good. 
It also includes a pre-made WebSocket proxy adapter for using non-browser 9P servers.
This proposes two new fields on V86Option's `filesystem` object:
```typescript
export interface V86Options {
// ...
filesystem?: {
// ...
/**
* A function that will be called for each 9p request.
* If specified, this will back Virtio9p instead of a filesystem.
* Use this …
```
> add support for custom 9p request handler
