Makefile

removing some superflorous spaces and fixing a syntax error that makes it unable to compile with GNU Make

clean up the Makefile

---

src/browser/main.js

closure compiler fails.
I'm assuming it should be settings, in either case closure compiler compiles and it works.

Change emulator.settings to settings

---

Readme.md

Fix typos in readme

---

LICENSE

Happy 2018!
IANAL, so I'm not sure how this stuff works, but I did manually verify that the project has had commits in every year (except 2012, which is the year the project started, so that's probably okay).

Update copyright year to 2018

---

src/vga.js

Return correct VGA CRTC index value in 3D4 read

---

src/browser/speaker.js
src/dma.js
src/sb16.js

- Reduces hearing loss. The PC speaker sounded much louder than everything else.
(*Volume will be adjustable later when the mixer chip gets implemented.*)
- Addresses exceptions: overlapped IO reads and non-finite / out-of-range oscillator frequencies.
- Addresses some bugs and some sound stuttering.

Some SB16 and PC Speaker improvements

---

docs/api.md

couldn't find this in the docs

add lock_mouse business

---

Readme.md

Readme: Fix typo

---

src/browser/starter.js

This implements #452 by publicly exposing existing internal API functionality.

Provide access to CPU memory via V86Starter

---

src/rust/cpu/cpu.rs
src/rust/wasmgen/wasm_builder.rs
tests/expect/run.js
tests/expect/tests/add.wast
tests/expect/tests/call-ret.wast
tests/expect/tests/do-while.wast
tests/expect/tests/if.wast
tests/expect/tests/inc.wast
tests/expect/tests/indirect-call.wast
tests/expect/tests/loop.wast
tests/expect/tests/mem32r.wast
tests/expect/tests/mem32rmw.wast
tests/expect/tests/mem32w.wast
tests/expect/tests/mov-immoffs.wast
tests/expect/tests/pop.wast
tests/expect/tests/push.wast
tests/expect/tests/sti.wast
tests/expect/tests/task_switch_test.wast
tests/expect/tests/task_switch_test_sse.wast
tests/expect/tests/while-do.wast

resize tlb_data to proper size

---

src/memory.js
src/rust/cpu/cpu.rs
src/rust/cpu/memory.rs

Mask values written to mmap_write{8,16}

---

src/main.js

If v86 is running in a Web Worker environment, use `queueMicrotask` for `fast_next_tick`.
With a worker thread dedicated to v86 we can run ticks without worrying about blocking the UI, but `setTimeout()` is still called every 256 ticks for a chance to run the `onmessage` callback.
Previously, `fast_next_tick` falls back to `setTimeout` and is slow.
CoreMark results under different configurations:
Main thread:
```
~ # coremark
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 11288
Total time (secs): 11.288000
Iterations/Sec   : 1771.793055
Iterations       : 20000
Compiler version : GCC8.3.0
Compiler flags   : -O2   -lrt
Memory location  : Please put data memory location here
(e.g. code in flash, data on heap etc)
seedcrc          : 0xe9f5
[0]crclist …
```

Use `queueMicrotask` for `fast_next_tick` in Web Worker environment.

---

lib/filesystem.js

Hi,
The PR fixes a simple typo.

fix simple typo

---

Readme.md

1. Updated Readme.md to include a new section for installing WSL dependencies
2. Added a WSL_setup.sh for installing v86 dependencies
This solves the DOS file format issue in Windows environment.

Add setup instructions for WSL (Windows 10 environment)

---

index.html
src/browser/main.js
src/browser/starter.js

addressed issue #333 
added a button in index.html to disable and enable sound during the session

added sound on/off button

---

src/browser/main.js

Added url config option for networking, audio, acpi.
Custom profile can now also be configured using the url.
#448

Added url config

---

src/ps2.js

Mouse Wheel Support [Microsoft Intellimouse].
Sorry for my code, but it is working.
Tested under KolibriOS.

Mouse Wheel Support

---

src/browser/starter.js

Allows system keybindings to be intercepted by the guest. I've been using this for a while now myself.

Add keyboard lock support

---

debug.html
index.html
src/browser/screen.js

Screenshot For Text Mode

---

Readme.md

I added my custom buildroot configs in the hopes that it would help someone who is looking for a starting point for building there own buildroot.

Add my buildroot configs

---

Readme.md

I have tested Ubuntu 16, and it works with v86.

Record that Ubuntu 16 works

---

examples/two_instances.html

You'll still need to assign a static IP to each VM, but they can communicate!

Connect guest network adapters

---

src/uart.js

Fixes issue described in https://github.com/copy/v86/issues/922
https://github.com/copy/v86/assets/2009870/cd368bea-62da-4e07-b501-278b9118610e
https://github.com/copy/v86/assets/2009870/a27f8761-821b-448c-9206-da5eaf46c130

Fix: Ctrl+C doesn't go to next line

---

examples/lang.html
examples/lua.html
examples/nodejs.js
examples/nodejs_state.js
examples/serial.html
examples/two_instances.html
examples/worker.js
src/browser/serial.js
src/uart.js
tests/api/reset.js
tests/api/serial.js
tests/benchmark/arch-bytemark.js
tests/benchmark/linux-boot.js
tests/devices/virtio_9p.js
tests/full/run.js
tests/jit-paging/run.js
tests/kvm-unit-tests/run.js
tests/qemu/run.js
tools/docker/debian/build-state.js

Fixes https://github.com/copy/v86/issues/927

Replace serial-output-char with serial-output-byte

---

v86.css

Prevent scrolling on canvas in touch screen

---

src/rust/cpu/pic.rs

pic: unmask all on icw1

---

debug.html
index.html
src/browser/main.js

Add bios input

---

src/browser/fetch_network.js

Fixed wrong reference to cors_proxy in fetch_network.js

Fixed broken FetchNetworkAdapter.cors_proxy attribute

---

src/browser/starter.js
src/lib.js
src/state.js

This fixes a problem saving state in nodejs with `nodejs-loader.mjs` and is more Idiomatic.

Change `instance of Array` to `Array.isArray`

---

Makefile
debug.html
nodejs-loader.mjs
src/browser/starter.js
src/cpu.js
src/rust/cpu/memory.rs
src/virtio_balloon.js
tests/devices/virtio_balloon.js

Adds a virtio balloon device to zero unused memory pages from the VM, reducing snapshot size.

Virtio balloon device

---

.github/workflows/ci.yml
Makefile
nodejs-loader.mjs

Also fix export in nodejs-loader.mjs

Build and publish libv86-debug as Module Script

---

docs/networking.md

The text is unchanged compared to my earlier submission, only removed commit and merge history from PR.

Comprehensive update to the networking documentation.

---

src/apic.js

apic: LVT Thermal Sensor

---

src/floppy.js

Several Linux kernels (not all) fail to detect v86's floppy controller, while other guest OSes detect it just fine.
After comparing the floppy debug output of different guest OSes and some head-scratching I eventually noticed that under certain circumstances, v86's floppy controller was raising an IRQ very early when it wasn't supposed to, and this lead to the failed floppy controller detection. See the commit message for a more detailed explanation.
This bugfix is not specific to Linux, this is only where this bug surfaced, other guest OSes might also benefit from this PR.
Fixes issue #1343, passed all tests available to me.
<details>
<summary>Debian 12 output with this PR applied, directly after boot</summary>
```
root@debian:~# uname -r
6.1.0-31-686-pae
root@debian:~# lsblk
NAME …
```

Fix floppy controller detection under Linux

---

src/rtc.js

rtc: set CMOS battery charge status, add diagnostic status register
